title: "Machine learning"
author: "Di Ye"
date: "Sunday, February 22, 2015"
output: html_document
---

Data input cleaning
---
```{r}
require(caret)
training<-read.csv("pml-training.csv",sep=",",header=TRUE,na.strings=c("NA",""),stringsAsFactors=FALSE,as.is=TRUE)
training$classe <- as.factor(training$classe)
training <- training[,-nearZeroVar(training)]
#The 1st to 7th columns are obviously not suitable for analysis hence we did not include them from data sets
training <- training[,-c(1,2,3,4,5,6,7)]
#Set the seed for reproduction
set.seed(111)
inTrain <- createDataPartition(y=training$classe, p=0.75, list=FALSE)
#Seperate training set and testing set
training <- training[inTrain,]
testing <- training[-inTrain,]
#There'are character data and na data in the data set, we use knnimpute and other methods to clean the data 
training<-training[,!sapply(training,is.character)]
pre<-preProcess(training[,-length(training)],method=c("center", "scale", "knnImpute", "pca"), thresh=0.95)
clean_data <- predict(pre,training[,-length(training)])
```
Exploratory analysis
```{r}
library(datasets);require(stats);require(graphics)
pairs(clean_data, panel = panel.smooth, main = "Accelerometers pair stats")
```
Model building
```{r}
#Random forest is used to perform machine learning
model<-train(training$classe ~.,data=clean_data, method="rf")
```
Validation
```{r}
#Test sets is used to validate the model and confusion matrix is shown for diagnosis
test <-predict(pre, testing[,-length(testing)])
confusionMatrix(testing$classe, predict(model,test))
```

